version: "3.8"
services:
  php:
    build:
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-app}
    extra_hosts:
      - "host.docker.internal:host-gateway"  # для работы x-debug, так как не во всех ОС есть хост host.docker.internal
    volumes:
      - ./source-code:/application # source-code - ваш путь до папки с php кодом